language: python

env:
  - TOX_ENV=py36
install:
  - git config --global user.email "bumpversion-test-git@travis.ci"
  - git config --global user.name "Testing Git on Travis CI"
  - git --version
  - git config --list
  - pip install --upgrade pytest tox

script:
  - tox -e $TOX_ENV

